Traceback (most recent call last):
  File "/home/goodpast/graha682/.local/lib/python3.6/site-packages/input_reader/key_adder.py", line 559, in _find_keys_in_input
    i = self._find_key(f, i, namespace)
  File "/home/goodpast/graha682/.local/lib/python3.6/site-packages/input_reader/key_adder.py", line 602, in _find_key
    inew, name, parsed = val._parse(f, i, namespace)
  File "/home/goodpast/graha682/.local/lib/python3.6/site-packages/input_reader/keylevel.py", line 286, in _parse
    raise ReaderError(self.name+msg)
input_reader.helpers.ReaderError: localize: expected 1 arguments, got 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/goodpast/graha682/.local/lib/python3.6/site-packages/input_reader/key_adder.py", line 559, in _find_keys_in_input
    i = self._find_key(f, i, namespace)
  File "/home/goodpast/graha682/.local/lib/python3.6/site-packages/input_reader/key_adder.py", line 602, in _find_key
    inew, name, parsed = val._parse(f, i, namespace)
  File "/home/goodpast/graha682/.local/lib/python3.6/site-packages/input_reader/key_adder.py", line 759, in _parse
    i, val = self._parse_key_level(f, i+1)
  File "/home/goodpast/graha682/.local/lib/python3.6/site-packages/input_reader/key_adder.py", line 542, in _parse_key_level
    i, namespace = self._find_keys_in_input(f, i, namespace)
  File "/home/goodpast/graha682/.local/lib/python3.6/site-packages/input_reader/key_adder.py", line 564, in _find_keys_in_input
    raise ReaderError (self.name+': '+str(e))
input_reader.helpers.ReaderError: scf: localize: expected 1 arguments, got 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/goodpast/graha682/code/python/scripts/pyscf_wrapper/run_pySCF.py", line 54, in <module>
    main()
  File "/home/goodpast/graha682/code/python/scripts/pyscf_wrapper/run_pySCF.py", line 32, in main
    inp = read_input(files)
  File "/panfs/roc/groups/13/goodpast/graha682/code/python/scripts/pyscf_wrapper/read_input.py", line 59, in read_input
    inp  = reader.read_input(filename)
  File "/home/goodpast/graha682/.local/lib/python3.6/site-packages/input_reader/input_reader.py", line 88, in read_input
    i, namespace = self._parse_key_level(f, 0)
  File "/home/goodpast/graha682/.local/lib/python3.6/site-packages/input_reader/key_adder.py", line 542, in _parse_key_level
    i, namespace = self._find_keys_in_input(f, i, namespace)
  File "/home/goodpast/graha682/.local/lib/python3.6/site-packages/input_reader/key_adder.py", line 564, in _find_keys_in_input
    raise ReaderError (self.name+': '+str(e))
input_reader.helpers.ReaderError: main: scf: localize: expected 1 arguments, got 0
Traceback (most recent call last):
  File "/home/goodpast/graha682/.local/lib/python3.6/site-packages/input_reader/key_adder.py", line 559, in _find_keys_in_input
    i = self._find_key(f, i, namespace)
  File "/home/goodpast/graha682/.local/lib/python3.6/site-packages/input_reader/key_adder.py", line 602, in _find_key
    inew, name, parsed = val._parse(f, i, namespace)
  File "/home/goodpast/graha682/.local/lib/python3.6/site-packages/input_reader/keylevel.py", line 303, in _parse
    raise ReaderError(self.name+msg)
input_reader.helpers.ReaderError: localize: expected 1 arguments, got 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/goodpast/graha682/.local/lib/python3.6/site-packages/input_reader/key_adder.py", line 559, in _find_keys_in_input
    i = self._find_key(f, i, namespace)
  File "/home/goodpast/graha682/.local/lib/python3.6/site-packages/input_reader/key_adder.py", line 602, in _find_key
    inew, name, parsed = val._parse(f, i, namespace)
  File "/home/goodpast/graha682/.local/lib/python3.6/site-packages/input_reader/key_adder.py", line 759, in _parse
    i, val = self._parse_key_level(f, i+1)
  File "/home/goodpast/graha682/.local/lib/python3.6/site-packages/input_reader/key_adder.py", line 542, in _parse_key_level
    i, namespace = self._find_keys_in_input(f, i, namespace)
  File "/home/goodpast/graha682/.local/lib/python3.6/site-packages/input_reader/key_adder.py", line 564, in _find_keys_in_input
    raise ReaderError (self.name+': '+str(e))
input_reader.helpers.ReaderError: scf: localize: expected 1 arguments, got 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/goodpast/graha682/code/python/scripts/pyscf_wrapper/run_pySCF.py", line 54, in <module>
    main()
  File "/home/goodpast/graha682/code/python/scripts/pyscf_wrapper/run_pySCF.py", line 32, in main
    inp = read_input(files)
  File "/panfs/roc/groups/13/goodpast/graha682/code/python/scripts/pyscf_wrapper/read_input.py", line 59, in read_input
    inp  = reader.read_input(filename)
  File "/home/goodpast/graha682/.local/lib/python3.6/site-packages/input_reader/input_reader.py", line 88, in read_input
    i, namespace = self._parse_key_level(f, 0)
  File "/home/goodpast/graha682/.local/lib/python3.6/site-packages/input_reader/key_adder.py", line 542, in _parse_key_level
    i, namespace = self._find_keys_in_input(f, i, namespace)
  File "/home/goodpast/graha682/.local/lib/python3.6/site-packages/input_reader/key_adder.py", line 564, in _find_keys_in_input
    raise ReaderError (self.name+': '+str(e))
input_reader.helpers.ReaderError: main: scf: localize: expected 1 arguments, got 2
