Traceback (most recent call last):
  File "/home/goodpast/graha682/code/python/freeze_and_thaw/cython/cmain.py", line 6, in <module>
    main.main(sys.argv[1])
  File "main.pyx", line 117, in main.main (main.c:4333)
    Fock, inp.mSCF[a], Dnew, eproj, err = do_embedding(a, inp,
  File "scf.pyx", line 94, in scf.do_embedding (scf.c:3599)
    Fock = inp.DIIS.update(Fock)
  File "/home/goodpast/graha682/code/python/pyscf/pyscf/lib/diis.py", line 221, in update
    w, v = scipy.linalg.eigh(h)
  File "/panfs/roc/msisoft/python-epd/1.5.2/Canopy_64bit/User/lib/python2.7/site-packages/scipy/linalg/decomp.py", line 387, in eigh
    raise LinAlgError("unrecoverable internal error.")
numpy.linalg.linalg.LinAlgError: unrecoverable internal error.
